'''
    INPUT:
        wrflda* data generated by "create_lda.py"

    OUTPUT:
        wrflda* files with zero values

    UPDATE:
        Xin Zhang:
            04/22/2020: basic
'''

import xarray as xr
import numpy as np
import pandas as pd

# set the date range of output files
st = '20190724 18:00'
et = '20190724 23:55'
dt = 5  # unit: min

# get basic file
datadir = './lda/'
base = 'wrflda_d03_2019-07-25_00:00:00'
ds = xr.open_dataset(datadir+base)

# load data and create zero DataArray
da = ds['LDACHECK']
ds['LDACHECK'] = da.copy(data=np.full_like(da, 0.))

# generate output filenames based on the date range
dr = pd.date_range(st, et, freq=str(dt)+'T')
filenames = [d.strftime(f'{base[:10]}_%Y-%m-%d_%H:%M:%S') for d in dr]

# create files (zero values) based on filenames
for tindex, f in enumerate(filenames):
    # generate 'Times' variable
    Times = xr.DataArray(np.array([dr[tindex]],
                                  dtype=np.dtype(('S', 19))),
                         dims=['Time'])
    ds['Times'] = Times

    ncfile = datadir + f
    print('Saving to {}'.format(ncfile))
    ds.to_netcdf(ncfile, format='NETCDF4',
                 encoding={
                          'Times': {
                             'zlib': True,
                             'complevel': 5,
                             'char_dim_name': 'DateStrLen'
                          },
                          'LDACHECK': {'zlib': True, 'complevel': 5}
                          },
                 unlimited_dims={'Time': True})
